---
php:
  version: 7.2
  user: www-data
  group: www-data
datahub:
  development: false
  repo_url: https://github.com/thedatahub/Datahub.git
  repo_dir: /opt/.repos/datahub/
  branch: master
  dir: /opt/datahub
  service_name: Datahub
  pagination_num_records: 25 
  nginx:
    listen_port: 80
    server_name: datahub.example.com
    #    document_root: "{{ (datahub['dir'], 'web') | path_join }}"
    #    index: "{{ 'app_dev.php' if datahub['development'] else 'app.php' }}"
    document_root: /opt/datahub/web
    # TODO differentiate between dev and production
    index: app_dev.php
  mongodb:
    host: 127.0.0.1
    port: 27017
    database: datahub
    username: datahub
  mailer:
    transport: gmail
  admin:
    username: admin
  consumer:
    username: importer
  oauth:
    application_name: importer
datahub_pipeline:
  dir: /opt/datahub-pipeline
  fixes:
    repo_url: https://github.com/VlaamseKunstcollectie/Datahub-Fixes.git
    repo_dir: /opt/.repos/datahub-fixes/
    branch: master
  authority_files:
    repo_url: https://github.com/VlaamseKunstcollectie/Authority-Files.git
    repo_dir: /opt/.repos/authority-files/
    branch: master
  eiz:
    url: https://cjm-web.adlibhosting.com/arthubflanders/oai.ashx
    set: vkc
  institutions:
    - name: Museum voor Schone Kunsten Gent
      shorthand: MSK
      fix_file_path: msk_oai_adlib.fix
    - name: Musea Brugge - Groeningemuseum
      shorthand: GRO
      fix_file_path: groeninge_oai_adlib.fix
    - name: Mu.ZEE, Kunstmuseum aan zee
      shorthand: MUZEE
      fix_file_path: muzee_oai_adlib.fix
datahub_dashboard:
  repo_url: https://github.com/thedatahub/Datahub-Dashboard.git
  repo_dir: /opt/.repos/datahub-dashboard/
  branch: master
  dir: /opt/datahub-dashboard
  service_name: Datahub Dashboard
  nginx:
    listen_port: 80
    server_name: dashboard.example.com
    #    document_root: "{{ (datahub_dashboard['dir'], 'web') | path_join }}"
    #    index: "{{ 'app_dev.php' if datahub_dashboard['development'] else 'app.php' }}"
    document_root: /opt/datahub-dashboard/web
    # TODO differentiate between dev and production
    index: app_dev.php
  mongodb:
    host: 127.0.0.1
    port: 27017
    database: datahub_dashboard
    username: datahub_dashboard
arthub:
  repo_url: https://github.com/VlaamseKunstcollectie/Arthub-Frontend
  repo_dir: /opt/.repos/arthub/
  branch: master
  dir: /opt/arthub
  nginx:
    listen_port: 80
    server_name: arthub.example.com
cronjobs:
  - /opt/datahub-pipeline/fixes/scripts/vocabularies.sh
