---
- name: "Copy nginx vhost for {{ vhost_name }}"
  template:
    src: "{{ vhost_type }}.vhost"
    dest: "/etc/nginx/sites-available/{{ vhost_name }}"
  notify: restart nginx

- name: "Create symlink for {{ vhost_name }} nginx vhost"
  file:
    src: "/etc/nginx/sites-available/{{ vhost_name }}"
    dest: "/etc/nginx/sites-enabled/{{ vhost_name }}"
    state: link
  notify: restart nginx

- name: Add domain to LetsEncrypt array to request SSL certificates at the end of the play
  set_fact:
    letsencrypt_domains: "{{ letsencrypt_domains }} + [ '{{ server_name }}' ]"
  when: vhost_ssl | length == 0
