---
- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Allow http through the firewall
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Allow https through the firewall
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Create sites-available and sites-enabled folder
  file:
    path: "/etc/nginx/sites-available"
    state: directory
    recurse: true

- name: Create sites-enabled folder
  file:
    path: "/etc/nginx/sites-enabled"
    state: directory
    recurse: true

- name: Set nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    notify: restart nginx
