---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Remove default nginx site (Debian/Ubuntu)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  when: ansible_os_family == "Debian"

- name: Remove default nginx config (AlmaLinux)
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx
  when: ansible_os_family == "RedHat"

- name: Enable and start nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure firewalld is running (RedHat)
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Open HTTP service in firewalld (RedHat)
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"

- name: Open HTTPS service in firewalld (RedHat)
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"

- name: Install htpasswd utility (apt)
  apt:
    name: apache2-utils
    state: present
  when: ansible_os_family == "Debian"

- name: Install htpasswd utility (dnf)
  dnf:
    name: httpd-tools
    state: present
  when: ansible_os_family == "RedHat"

- name: Create nginx htpasswd file
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ nginx.auth_basic_username }}"
    password: "{{ nginx.auth_basic_password }}"
  when:
    - nginx.auth_basic_username is defined
    - nginx.auth_basic_password is defined
