---
- name: Install nginx on Debian/Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'

- name: Install nginx on AlmaLinux
  dnf:
    name: nginx
    state: present
  when: ansible_facts.distribution == 'AlmaLinux'

- name: Delete default nginx vhost symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Enable nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: Create htpasswd entry if needed
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ nginx.auth_basic_username }}"
    password: "{{ nginx.auth_basic_password }}"
  when: nginx.auth_basic_username is defined and nginx.auth_basic_password is defined
