---
- name: Load OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add apt repository if needed
  include_tasks: add_apt_repository.yml
  when:
    - ansible_os_family == 'Debian'
    - php.use_sury_repo | bool

- name: Install PHP-FPM and extensions
  package:
    name: "{{ php_packages }}"
    state: present

- name: Copy php.ini
  template:
    src: php.ini
    dest: "{{ php_ini_path }}"
  notify: restart php-fpm

- name: Enable and start PHP-FPM
  service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: yes
