---
- name: Add apt repository if needed
  include_tasks: add_apt_repository.yml
  when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10'

- name: Install php-fpm and deps
  apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-cli
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-curl
      - php{{ php_version }}-mongodb
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-dev
      - php-pear
      - composer=1.*
    state: present

# First run of install will output a huge error, but this can be safely ignored
- name: Install mongodb through pear
  community.general.pear:
    name: pecl/mongodb
    state: present
  ignore_errors: yes
  no_log: yes

- name: Copy php.ini
  template: src=php.ini dest=/etc/php/{{ php_version }}/fpm/php.ini
  notify: restart php-fpm

- name: Enable php-fpm service
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes
