---
- name: Determine distribution codename
  set_fact:
    distro_codename: "{{ ansible_facts.lsb.codename | default(ansible_facts.os_release.codename, true) }}"

- name: Set MongoDB APT repository URL for Debian
  set_fact:
    mongodb_pgp_url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    mongodb_apt_repository: "deb [arch=amd64,arm64] http://repo.mongodb.org/apt/debian {{ distro_codename }}/mongodb-org/{{ mongodb_version }} main"
  when: ansible_facts.distribution == 'Debian'

- name: Set MongoDB APT repository URL for Ubuntu
  set_fact:
    mongodb_pgp_url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    mongodb_apt_repository: "deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu {{ distro_codename }}/mongodb-org/{{ mongodb_version }} multiverse"
  when: ansible_facts.distribution == 'Ubuntu'

- name: Add MongoDB signing key
  apt_key:
    url: "{{ mongodb_pgp_url }}"
    state: present

- name: Add MongoDB APT repository
  apt_repository:
    repo: "{{ mongodb_apt_repository }}"
    state: present
    filename: "mongodb"
