nginx_vhost_available_dir: /etc/nginx/sites-available
nginx_vhost_enabled_dir: /etc/nginx/sites-enabled
nginx_vhost_use_symlink: true

nginx_fastcgi_params_file: /etc/nginx/fastcgi_params
nginx_log_dir: /var/log/nginx
