nginx_vhost_available_dir: /etc/nginx/sites-available
nginx_vhost_enabled_dir: /etc/nginx/sites-enabled
nginx_vhost_use_symlink: true

nginx_fastcgi_params_file: /etc/nginx/fastcgi_params
nginx_log_dir: /var/log/nginx

php_fpm_socket_dir: /run/php
php_fpm_socket_prefix: "php{{ php.version }}-fpm-"
php_fpm_socket_suffix: "-fpm.sock"
php_fpm_socket_pattern: "{{ php_fpm_socket_prefix }}{{ vhost.php_socket_name }}{{ php_fpm_socket_suffix }}"
