nginx_vhost_available_dir: /etc/nginx/conf.d
nginx_vhost_enabled_dir: /etc/nginx/conf.d
nginx_vhost_use_symlink: false

nginx_fastcgi_params_file: /etc/nginx/fastcgi.conf
nginx_log_dir: /var/log/nginx

php_fpm_socket_dir: /run/php-fpm
php_fpm_socket_pattern: "{{ vhost.php_socket_name }}.sock"
