---
- name: Install nginx, and php-fpm
  hosts: datahub
  remote_user: root

  roles:
    - common
    - php-fpm
    - nginx
    - mongodb
    - datahub
    - datahub-pipeline
    - datahub-dashboard
    - arthub
    - cron
