---
- name: Install common packages
  hosts: resourcespace
  roles:
    - common

- name: Install mariadb
  hosts: resourcespace
  roles:
    - mariadb

- name: Install ResourceSpace
  hosts: resourcespace
  roles:
    - resourcespace

- name: Install cantaloupe
  hosts: cantaloupe
  roles:
    - cantaloupe

- name: Install Imagehub
  hosts: imagehub
  roles:
    - imagehub

- name: Setup ResourceSpace
  hosts: resourcespace
  roles:
    - resourcespace_setup

- name: Set up cronjob
  hosts: datahub,datahub_pipeline,datahub_dashboard,arthub
  roles:
    - cron

- name: Set up SSL Certificates through LetsEncrypt
  hosts: datahub,datahub_pipeline,datahub_dashboard,arthub
  roles:
    - name: certbot
      when: letsencrypt_vhosts | length > 0
