---
- name: Include redirect nginx vhost
  include_role:
    name: nginx
    tasks_from: create_vhost.yml
    apply:
      vars:
        nginx_vhost:
          server_name: "{{ item.server_name }}"
          name: "{{ item.name }}"
          redirect_to: "{{ item.redirect_to }}"
          type: redirect
          ssl: "{{ item.ssl }}"
          redirect_to_https: "{{ item.redirect_to_https | default(true) }}"
          auth_basic: "{{ item.auth_basic | default('') }}"
          auth_basic_whitelist: "{{ item.auth_basic_whitelist | default([]) }}"
  with_items: "{{ domain_redirects }}"
