---
- name: Create cron folder
  file:
    path: "{{ cron_dir }}/cron/"
    state: directory
    recurse: true
    owner: "{{ application_user }}"
    group: "{{ application_user }}"

- name: Provide crontab entry to restart Cantaloupe image server once per day
  cron:
    name: "Restart Cantaloupe"
    minute: "50"
    hour: "19"
    user: "root"
    job: "systemctl restart {{ cantaloupe.service_name }}"
  when: is_cantaloupe

- name: Add additional cronjobs at the end if needed
  set_fact:
    cronjobs: "{{ cronjobs }} + {{ final_cronjobs }}"

- name: Create shell script for cron task
  template:
    src: cronjobs.sh
    dest: "{{ cron_dir }}/cron/import_data.sh"
    mode: '755'

- name: Provide crontab entry for daily reload of arthub records
  cron:
    name: "Reload {{ cron_name }} records"
    minute: "0"
    hour: "20"
    user: "{{ application_user }}"
    job: "bash {{ cron_dir }}/cron/import_data.sh > {{ cron_dir }}/cron/output.log 2>&1"

- name: Renew SSL certificates through LetsEncrypt
  cron:
    name: "Renew {{ cron_name }} LetsEncrypt certificates"
    minute: "0"
    hour: "20"
    user: "root"
    job: "certbot renew -n -q --agree-tos --webroot -w /var/lib/letsencrypt/"
    state: "{{ 'present' if (letsencrypt_vhosts | length > 0) else 'absent' }}"

- name: Add FTP upload cronjob if needed
  cron:
    name: "Put files uploaded through FTP into ResourceSpace"
    minute: "*/5"
    user: "{{ application_user }}"
    job: "php {{ imagehub.dir }}/bin/console app:ftp-to-resourcespace -vvv >> {{ cron_dir }}/cron/imagehub_ftp_output.log 2>&1"
  when: imagehub.ftp_cronjob

- name: Configure offline jobs for ResourceSpace
  cron:
    name: "Run ResourceSpace offline jobs"
    minute: "0"
    hour: "20"
    user: "root"
    job: "cd {{ resourcespace.repo_dir }}/pages/tools; php offline_jobs.php >> {{ cron_dir }}/cron/resourcespace_cron_output.log 2>&1; cd {{ resourcespace.repo_dir }}/batch; php create_previews.php >> {{ cron_dir }}/cron/resourcespace_cron_output.log 2>&1"
    state: "present"
  when: is_resourcespace

- name: Set cronjobs for arthub check task
  set_fact:
    cronjobs:
      - "date \"+%Y-%m-%d %H:%M:%S\" >> {{ cron_dir }}/cron/check_arthub.log"
      - "curl -s -o /dev/null -I -L -w \"%{http_code}\" '{{ arthub.nginx.server_name }}/nl' | grep 200 || /usr/sbin/service arthub restart"
  when: is_arthub is defined and is_arthub

- name: Create shell script for arthub check task
  template:
    src: cronjobs.sh
    dest: "{{ cron_dir }}/cron/check_arthub.sh"
    mode: '755'
  with_items: "{{ cronjobs }}"
  when: is_arthub is defined and is_arthub

- name: Provide crontab entry to check for failure and restart when needed
  cron:
    name: "Check and restart {{ cron_name }} Arthub if needed"
    user: "root"
    job: "bash {{ cron_dir }}/cron/check_arthub.sh >> {{ cron_dir }}/cron/check_arthub.log 2>&1"
  when: is_arthub is defined and is_arthub

- name: Create shell script for root cron task
  template:
    src: root_cronjobs.sh
    dest: "{{ cron_dir }}/cron/root_cronjobs.sh"
    mode: '755'
    owner: root
    group: root
  when: root_cronjobs | length > 0

- name: Set cronjobs for root user
  cron:
    name: "Additional root cronjobs"
    minute: "0"
    hour: "21"
    user: "root"
    job: "bash {{ cron_dir }}/cron/root_cronjobs.sh"
  when: root_cronjobs | length > 0
