---
- name: Set pipeline datahub_url when undefined
  set_fact:
    datahub_pipeline: >-
      {{
        datahub_pipeline | combine({
          'datahub_url': datahub_pipeline.datahub_protocol ~ '://' ~ datahub.nginx.server_name
        }, recursive=true)
      }}
  when: datahub_pipeline.datahub_url is undefined

- name: Normalize pipeline directory paths
  set_fact:
    datahub_pipeline: >-
      {{
        datahub_pipeline | combine({
          'dir': datahub_pipeline.dir | regex_replace('\\/$', ''),
          'fixes': {
            'repo_dir': datahub_pipeline.fixes.repo_dir | regex_replace('\\/$', '')
          },
          'authority_files': {
            'repo_dir': datahub_pipeline.authority_files.repo_dir | regex_replace('\\/$', '')
          }
        }, recursive=true)
      }}

- name: Initialize datahub_pipeline_paths array
  set_fact:
    datahub_pipeline_fix_file_paths: {}

- name: Set absolute paths for fix file paths and store them in the new array
  set_fact:
    datahub_pipeline_fix_file_paths: >-
      {{
        datahub_pipeline_fix_file_paths | combine({
          item.shorthand:
            (
              datahub_pipeline.dir ~ '/fixes/' ~ item.fix_file_path
            )
            if not item.fix_file_path.startswith('/')
            else item.fix_file_path
        })
      }}
  loop: "{{ datahub_pipeline.institutions }}"

- name: Install base system packages on Debian/Ubuntu
  apt:
    name:
      - perl
      - git
      - make
      - gcc
      - sqlite3
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install base system packages on AlmaLinux/RHEL
  dnf:
    name:
      - perl
      - git
      - make
      - gcc
      - sqlite
    state: present
  when: ansible_os_family == "RedHat"

- name: Install cpanminus package
  package:
    name: "{{ 'cpanminus' if ansible_os_family == 'Debian' else 'perl-App-cpanminus' }}"
    state: present

- name: Install development libraries on Debian systems
  package:
    name:
      - build-essential
      - pkg-config
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libexpat1-dev
      - libsqlite3-dev
      - default-libmysqlclient-dev
      - libdbd-mysql-perl
      - libdbd-sqlite3-perl
      - libcrypt-ssleay-perl
      - libcatmandu-perl
      - libcatmandu-xml-perl
      - libcatmandu-oai-perl
      - libcatmandu-viaf-perl
      - libcatmandu-aat-perl
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install development libraries on RedHat systems
  package:
    name:
      - openssl-devel
      - libxml2-devel
      - libxslt-devel
      - expat-devel
      - sqlite-devel
      - mariadb-devel
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure local perl5 directory exists in application home
  file:
    path: "{{ application_user_homedir }}/perl5"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
    mode: "0755"

- name: Install MariadB, legacy Rackspace CloudFiles and Catmandu Perl dependencies on RedHat
  cpanm:
    name: "{{ item }}"
    locallib: "{{ application_user_homedir }}/perl5"
    notest: true
  loop:
    - DBD::MariaDB
    - WebService::Rackspace::CloudFiles
    - Catmandu
    - Catmandu::XML
    - Catmandu::OAI
    - Catmandu::VIAF
    - Catmandu::AAT
  become_user: "{{ application_user }}"
  environment:
    PERL5LIB: "{{ application_user_homedir }}/perl5/lib/perl5"
    PATH: "{{ application_user_homedir }}/perl5/bin:{{ ansible_env.PATH }}"
    MARIADB_CONFIG: "{{ '/usr/bin/mariadb_config' }}"
  when: ansible_os_family == "RedHat"

- name: Install additional Datahub pipeline Perl modules
  cpanm:
    name: "{{ item }}"
    locallib: "{{ application_user_homedir }}/perl5"
  loop:
    - Datahub::Factory
    - Datahub::Factory::Cmd
    - Datahub::Factory::Importer::EIZ
    - Datahub::Factory::Exporter
  become_user: "{{ application_user }}"
  environment:
    PERL5LIB: "{{ application_user_homedir }}/perl5/lib/perl5"
    PATH: "{{ application_user_homedir }}/perl5/bin:{{ ansible_env.PATH }}"
    MARIADB_CONFIG: "{{ '/usr/bin/mariadb_config' if ansible_os_family == 'RedHat' else omit }}"

- name: Find perl modules
  find:
    paths: "{{ application_user_homedir }}/perl5/lib/perl5"
    patterns: "{{ datahub_pipeline.perl_module_overrides }}"
    file_type: file
    recurse: true
  register: perl_modules

- name: Check if backup exists
  stat:
    path: "{{ item.path }}_old"
  loop: "{{ perl_modules.files }}"
  register: perl_backup_stats

- name: Backup original module
  copy:
    src: "{{ item.0.path }}"
    dest: "{{ item.0.path }}_old"
    remote_src: true
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
    mode: "0644"
  become_user: "{{ application_user }}"
  loop: "{{ perl_modules.files | zip(perl_backup_stats.results) | list }}"
  when: not item.1.stat.exists

- name: Deploy override module
  copy:
    src: "{{ item.path | basename }}"
    dest: "{{ item.path }}"
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
    mode: "0644"
  become_user: "{{ application_user }}"
  loop: "{{ perl_modules.files }}"

- name: Create main datahub pipeline directory
  file:
    path: "{{ datahub_pipeline.dir }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_user }}"

- name: Create pipeline repository directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
  loop:
    - "{{ datahub_pipeline.fixes.repo_dir }}"
    - "{{ datahub_pipeline.authority_files.repo_dir }}"

- name: Clone pipeline repositories
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}/repo/"
    version: "{{ item.branch }}"
    force: true
  become_user: "{{ application_user }}"
  loop:
    - url: "{{ datahub_pipeline.fixes.repo_url }}"
      dest: "{{ datahub_pipeline.fixes.repo_dir }}"
      branch: "{{ datahub_pipeline.fixes.branch }}"
    - url: "{{ datahub_pipeline.authority_files.repo_url }}"
      dest: "{{ datahub_pipeline.authority_files.repo_dir }}"
      branch: "{{ datahub_pipeline.authority_files.branch }}"

- name: Deploy customized vocabularies.sh script
  template:
    src: vocabularies.sh
    dest: "{{ datahub_pipeline.fixes.repo_dir }}/repo/scripts/vocabularies.sh"
  become_user: "{{ application_user }}"

- name: Deploy single datahub.ini configuration file (EIZ)
  template:
    src: datahub.ini
    dest: "{{ datahub_pipeline.dir }}/datahub.ini"
  become_user: "{{ application_user }}"
  when: datahub_pipeline.ini_configs is not defined

- name: Deploy multi datahub ini configs (KMSKA)
  template:
    src: "{{ item.value.template }}"
    dest: "{{ datahub_pipeline.dir }}/{{ item.value.dest }}"
  loop: "{{ datahub_pipeline.ini_configs | dict2items }}"
  vars:
    generate_temp_tables: "{{ item.value.generate_temp_tables | default(false) }}"
    set: "{{ item.value.set | default('') }}"
    anet_url: "{{ item.value.anet_url | default('') }}"
    fix_file_path: >-
      {{
        (
          datahub_pipeline.dir ~ '/fixes/' ~ item.value.fix_file
        )
        if (
          item.value.fix_file is defined and
          not item.value.fix_file.startswith('/')
        )
        else item.value.fix_file
      }}
    datahub_url: "{{ item.value.datahub_url | default('') }}"
    oauth_client_id: "{{ item.value.oauth_client_id | default('') }}"
    oauth_secret: "{{ item.value.oauth_secret | default('') }}"
    oauth_username: "{{ item.value.oauth_username | default('') }}"
    oauth_password: "{{ item.value.oauth_password | default('') }}"
  become_user: "{{ application_user }}"
  when: datahub_pipeline.ini_configs is defined

- name: Create symlinks to pipeline repositories
  file:
    src: "{{ item.src }}/repo/"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
  loop:
    - src: "{{ datahub_pipeline.fixes.repo_dir }}"
      dest: "{{ datahub_pipeline.dir }}/fixes"
    - src: "{{ datahub_pipeline.authority_files.repo_dir }}"
      dest: "{{ datahub_pipeline.dir }}/authority_files"
