---
- name: Add apt repository
  include_tasks: add_apt_repository.yml

# apt update currently not working, disabled for now
#- name: Update apt repositories
#  apt:
#    update_cache: true

- name: Install MariaDB
  apt:
    name:
      - mariadb-server

- name: Install python-pymysql when python 2.*
  apt:
    name:
      - python-pymysql
  when: ansible_python_version is match("2\..*")

- name: Install python3-pymysql when python 3.*
  apt:
    name:
      - python3-pymysql
  when: ansible_python_version is match("3\..*")
