---
- name: Install MariaDB
  dnf:
    name:
      - mariadb-server

- name: Install python-pymysql when python 2.*
  dnf:
    name:
      - python-pymysql
  when: ansible_python_version is match("2\..*")

- name: Install python3-pymysql when python 3.*
  dnf:
    name:
      - python3-pymysql
  when: ansible_python_version is match("3\..*")
