---
- name: Install MariaDB server
  package:
    name: mariadb-server
    state: present

- name: Install Python MySQL driver
  package:
    name: >-
      {{ 'python3-pymysql'
         if ansible_os_family == 'Debian'
         else 'python3-PyMySQL' }}
    state: present

- name: Enable and start MariaDB
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Set MariaDB root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password | default('') }}"
    login_unix_socket: >-
      {{ '/var/run/mysqld/mysqld.sock'
         if ansible_os_family == 'Debian'
         else '/var/lib/mysql/mysql.sock' }}
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
    state: present
    update_password: on_create
