---
- name: Install MariaDB for Debian/Ubuntu
  include_tasks: install_mariadb_debian.yml
  when: ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'

- name: Install MariaDB for AlmaLinux
  include_tasks: install_mariadb_almalinux.yml
  when: ansible_facts.distribution == 'AlmaLinux'

- name: Update MariaDB password for root account
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_password: "{{ mariadb_root_password }}"
    host: "localhost"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
