---
- name: Add apt repository
  include_tasks: add_apt_repository.yml

- name: Install MariaDB
  apt:
    name:
      - mariadb-server
      - python-pymysql

- name: update mysql password for root account
  mysql_user:
    name: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    password: '{{ mariadb_root_password }}'
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true

