php_packages:
  - php
  - php-fpm
  - php-cli
  - php-apcu
  - php-intl
  - php-mbstring
  - php-curl
  - php-xml
  - php-zip
  - php-mysqlnd
  - php-mongodb
  - composer

php_ini_path: "/etc/php.ini"
php_fpm_service: "php-fpm"
php_fpm_pool_dir: /etc/php-fpm.d
php_fpm_socket_dir: /run/php-fpm
php_fpm_socket_prefix: ""
php_fpm_socket_suffix: .sock
