---
parameters:
  # The first locale in the list is the default locale
  locales:
    - en
    - nl

  datahub_url: '{{ condition_reports.datahub_url }}'
  datahub_language: nl
  datahub_namespace: 'lido'
  datahub_metadataprefix: 'oai_lido'
{% if condition_reports.placeholder_images|length > 0 %}
  placeholder_images:
{% for image in condition_reports.placeholder_images %}
    - '{{ image }}'
{% endfor %}
{% else %}
  placeholder_images: []
{% endif %}

  # Certificate Authority (also known as 'cacert') may not work on its own depending on your system and PHP configuration,
  # that's why a cacert.pem is included in this project (from https://curl.haxx.se/docs/caextract.html).
  # Set override_certificate_authority to 'true' when we need to specify our own cacert.pem (can be a relative path or an absolute system path).
  override_certificate_authority: false
  ssl_certificate_authority_file: 'cacert.pem'

  datahub_data_definition:
    id:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/repositoryWrap/repositorySet/workID[@type="object-number"]'
    title_nl:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@xml:lang="nl"]'
    title_en:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@xml:lang="en"]'
    description_nl:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue'
    creator_nl:
      parent_xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor[not(actorInRole/attributionQualifierActor)]/actorInRole'
      xpath_main: 'actor/nameActorSet/appellationValue[@pref="preferred"]'
      xpath_sub: 'roleActor/term[@xml:lang="nl"]'
    creator_en:
      parent_xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor[not(actorInRole/attributionQualifierActor)]/actorInRole'
      xpath_main: 'actor/nameActorSet/appellationValue[@pref="preferred"]'
      xpath_sub: 'roleActor/term[@xml:lang="en"]'
    creator_role:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor[not(actorInRole/attributionQualifierActor)]/actorInRole/roleActor/term'
    technique_nl:
      xpath: '(descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/displayMaterialsTech[@xml:lang="nl"])[1]'
    technique_en:
      xpath: '(descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/displayMaterialsTech[@xml:lang="en"])[1]'
    earliest_date:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/earliestDate'
    latest_date:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/latestDate'
    publisher:
      xpath: 'administrativeMetadata[@xml:lang="{language}"]/recordWrap/recordSource/legalBodyName/appellationValue'
    copyright:
      xpath: 'administrativeMetadata[@xml:lang="{language}"]/rightsWorkWrap/rightsWorkSet/creditLine'
    handling_nl:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet[@type="handling"]/descriptiveNoteValue[@xml:lang="nl"]'
    handling_en:
      xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet[@type="handling"]/descriptiveNoteValue[@xml:lang="en"]'
    iiif_manifest_url:
      xpath: 'administrativeMetadata[@xml:lang="{language}"]/resourceWrap/resourceSet[resourceType/term="IIIF Manifest"]/resourceID[contains(@source, "Imagehub")]'
    iiif_image_url:
      xpath: 'administrativeMetadata[@xml:lang="{language}"]/resourceWrap/resourceSet[resourceType/term="thumbnail"]/resourceID[contains(@source, "Imagehub")]'

  service_url: '{{ condition_reports.service_url }}'

  validate_manifests: false
  validator_url: 'http://localhost:8080/validate?url='

  authentication_url: '{{ condition_reports.authentication_url }}'
  authentication_whitelist:
    - '127.0.0.1'
  authentication_service_description:
    confirmLabel: 'Login'
    description: '{{ condition_reports.authentication_service_description }}'
    failureDescription: 'Authentication failed'
    failureHeader: 'Authentication Failed'
    header: 'Please log in'
    label: 'Login to the Flemish Art Collection'
    profile: 'http://iiif.io/api/auth/1/login'
