---
- name: Update package cache (apt)
  shell: apt update
  become: true
  when: ansible_os_family == "Debian"

- name: Update package cache (dnf)
  dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install base packages (Ubuntu)
  apt:
    name:
      - git
      - screen
      - curl
      - software-properties-common
      - dirmngr
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install base packages (Debian)
  apt:
    name:
      - git
      - screen
      - curl
      - dirmngr
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Install base packages (AlmaLinux)
  dnf:
    name:
      - git
      - screen
      - curl
      - ca-certificates
      - gnupg2
      - policycoreutils-python-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Python 3 packages (apt)
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - python3-passlib
    state: present
  when: ansible_os_family == "Debian"

- name: Install Python 3 packages (dnf)
  dnf:
    name:
      - python3-pip
      - python3-setuptools
      - python3-passlib
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure application user exists
  user:
    name: "{{ application_user }}"
    password: "{{ application_password | password_hash('sha512') }}"
    state: present
