---
- name: Install common packages Debian/Ubuntu
  include_tasks: install_common_debian.yml
  when: ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'

- name: Install common packages for AlmaLinux
  include_tasks: install_common_almalinux.yml
  when: ansible_facts.distribution == 'AlmaLinux'

- name: Create application user if it does not yet exist
  user:
    name: "{{ application_user }}"
    password: "{{ application_password | password_hash('sha512') }}"
    state: present
