---
- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install git, pip, virtualenv, setuptools, software-properties-common, apt-transport-https and ca-certificates
  apt:
    name:
      - git
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - software-properties-common
      - apt-transport-https
      - ca-certificates

- name: Create application user if it does not yet exist
  user:
    name: "{{ application_user }}"
    password: "{{ application_password | password_hash('sha512') }}"
    state: present
