---
- name: Copy imagehub.yaml for imagehub
  template:
    src: imagehub.yaml
    dest: "{{ imagehub.repo_dir }}/repo/config/imagehub.yaml"
  become_user: "{{ application_user }}"

- name: Provide crontab entry for daily update of ResourceSpace data and generation of manifests
  set_fact:
    cronjobs: "{{ cronjobs }} + [  'php {{ imagehub.dir }}/bin/console app:datahub-to-resourcespace', 'php {{ imagehub.dir }}/bin/console app:generate-iiif-manifests' ]"

