parameters:
    # Url should have a trailing slash
    resourcespace_api_url: '{{ imagehub.resourcespace_api_url }}'
    resourcespace_api_username: '{{ imagehub.resourcespace_api_username }}'
    resourcespace_api_key: '{{ rs_api_key }}'

    datahub_url: '{{ imagehub.datahub_url }}'

    datahub_language: nl
    datahub_namespace: 'lido'
    datahub_metadataprefix: 'oai_lido'
    datahub_related_works_xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectRelationWrap/relatedWorksWrap/relatedWorkSet'
    store_datahub_record_ids: {{ imagehub.store_datahub_record_ids }}

    placeholder_id: {{ imagehub.placeholder_id }}

    # The value of 'field' within each definition is the shorthand name of the field in ResourceSpace where this data is sent.
    # These fields should not be manually edited in ResourceSpace, as any data within will automatically be overwritten with data from the Datahub!
    # Field 'id' must always be present in the data definition (= inventory number, used a primary key in MySQL).
    # Field 'dh_record_id' is a reserved keyword and should never be used (used to link inventory numbers with datahub records).
    datahub_data_definition:
        id:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/repositoryWrap/repositorySet/workID[@type="object-number"]'
            field: 'id'
        work_pid:
            xpath: 'objectPublishedID'
            field: 'pidobject'
        title_nl:
            xpath: '(descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@pref="preferred"])[1]'
            field: 'nl-titleartwork'
        title_en:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@xml:lang="en"]'
            field: 'en-titleartwork'
        short_description:
            xpath: '(descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue)[1]'
            field: 'description'
        creator:
            xpath: '(descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor[not(actorInRole/attributionQualifierActor)]/actorInRole/actor/nameActorSet/appellationValue[@pref="preferred"])[1]'
            field: 'creatorofartworkobje'
        creator_role:
            xpath: '(descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor[not(actorInRole/attributionQualifierActor)]/actorInRole/roleActor/term)[1]'
            field: 'roleofcreatorofartworkobje'
        earliest_date:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/earliestDate'
            field: 'earliestdate'
        latest_date:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/latestDate'
            label: 'latestdate'
        publisher:
            xpath: '(administrativeMetadata[@xml:lang="{language}"]/recordWrap/recordSource/legalBodyName/appellationValue)[1]'
            field: 'publisher'
        keywords:
            xpaths:
              - 'descriptiveMetadata[@xml:lang="{language}"]/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/conceptID[@source="AAT"]'
              - 'descriptiveMetadata[@xml:lang="{language}"]/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/term[@pref="preferred"]'
            field: 'keywords'
        copyright:
            xpath: 'administrativeMetadata[@xml:lang="{language}"]/rightsWorkWrap/rightsWorkSet/creditLine'
            field: 'copyrightnoticeofart'

    meemoo:
      service_url: '{{ imagehub.meemoo_service_url }}'
      iiif_url: 'https://images.meemoo.be/iiif/'
      inventory_url: 'https://images.meemoo.be/inventory'
      csv_headers:
        id: 'Dynamic.PID'
        publisher: 'Dynamic.dc_titles.archief'
        inventory_number: 'Dynamic.dc_identifier_localids.Inventarisnummer'
        copyright: 'Dynamic.dc_rights_credit'
        width: 'Technical.Width'
        height: 'Technical.Height'
        photographer: 'Descriptive.Authors.Author'
        title: 'Descriptive.Title'
        creator: 'Dynamic.dc_creators.Maker'
        url: 'url'
      url_regex_replace: '/^(https:\/\/images\.meemoo\.be\/iiif\/.*)\/full\/full\/0\/default\.jpg$/'
      url_regex_replace_with: '$1'
      iiif_rights_source: 'copyright'
      iiif_label:
        en: 'title'
        nl: 'title'
      iiif_required_statement:
        label:
          en: 'Attribution/Collection'
          nl: 'Attributie/Collectie'
        value:
          en: 'publisher'
          nl: 'publisher'
        extra_info:
          en: '{{ imagehub.credit_extra_info_en }}'
          nl: '{{ imagehub.credit_extra_info_nl }}'
      iiif_metadata_fields:
        title:
          label:
            en: 'Title'
            nl: 'Titel'
          value:
            en: 'title'
            nl: 'title'
        creator:
          label:
            en: 'Creator'
            nl: 'Vervaardiger'
          value:
            en: 'creator'
            nl: 'creator'
        inventory_number:
          label:
            en: 'Inventory no.'
            nl: 'Inventarisnummer'
          value:
            en: 'inventory_number'
            nl: 'inventory_number'
        creator_of_image:
          label:
            en: 'Photographer'
            nl: 'Fotograaf'
          value:
            en: 'photographer'
            nl: 'photographer'

    credit_line:
        nl:
          field: 'nl-creditline'
          title_field: 'nl-titleartwork'
          suffix: '{{ imagehub.credit_suffix_nl }}'
          sabam_suffix: 'België'
          invnr: 'Inv.nr.'
          photo: 'Foto'
          photographer: 'Fotograaf'
        en:
          field: 'en-creditline'
          title_field: 'en-titleartwork'
          suffix: '{{ imagehub.credit_suffix_en }}'
          sabam_suffix: 'Belgium'
          invnr: 'Inv.no.'
          photo: 'Photo'
          photographer: 'Photographer'

    iiif_versions:
{% for value in imagehub.iiif_versions %}
      - {{ value }}
{% endfor %}

    manifest_languages:
{% for value in imagehub.manifest_languages %}
      - {{ value }}
{% endfor %}

    main_iiif_version: {{ imagehub.main_iiif_version }}

    cantaloupe_url: '{{ imagehub.cantaloupe_url }}'
    cantaloupe_curl_opts:
        CURLOPT_SSL_VERIFYHOST: false
        CURLOPT_SSL_VERIFYPEER: false
#        CURLOPT_CAINFO: /path/to/cacert.pem
#        CURLOPT_CAPATH: /path/to/cacert.pem

    service_url: '{{ imagehub.service_url }}'

    resourcespace_manifest_field: 'pidafbeelding'

    validate_manifests: false
    validator_url: 'http://localhost:8080/validate?url='

    adfs_requirements:
      public: {{ imagehub.public | to_json }}
      key: '{{ imagehub.adfs_key }}'
      values: 
{% for value in imagehub.adfs_values %}
        - {{ value }}
{% endfor %}

    public_use:
      key: 'clearedforusage'
      value: 'Public use'
      # We need to encode the '/' character into %2F
      public_folder: 'public%2F'
      private_folder: 'private%2F'

    recommended_for_publication:
      key: 'recommendedimageforp'
    iiif_sort_number:
      key: 'iiifsortnumber'

    authentication_url: '{{ imagehub.authentication_url }}'
    authentication_whitelist:
      - '127.0.0.1'
    authentication_service_description:
      confirmLabel: 'Login'
      description: '{{ imagehub.auth_description }}'
      failureDescription: 'Authentication failed'
      failureHeader: 'Authentication Failed'
      header: 'Please log in'
      label: '{{ imagehub.auth_label }}'
      profile: 'http://iiif.io/api/auth/1/login'

    iiif2_label: 'nl-titleartwork'
    iiif2_attribution: 'publisher'

    publishers:
        Koninklijk Museum voor Schone Kunsten Antwerpen:
          translations:
            en: Royal Museum of Fine Arts Antwerp - Flemish Community
            nl: Koninklijk Museum voor Schone Kunsten Antwerpen - Vlaamse Gemeenschap
          creditline:
            en: '<p>De jpg-bestanden van kunstwerken in het publieke domein zijn downloadbaar in hoge resolutie via de website van KMSKA. Beelden aanvragen kan via het contactformulier op <a href="https://kmska.be/nl/contact">kmska.be/nl/contact</a>.</p>'
            nl: '<p>The jpg files of public domain artworks are downloadable in high resolution through the KMSKA website. Requesting images can be done through the contact form at <a href="https://kmska.be/en/contact">kmska.be/en/contact</a>.</p>'
        Museum voor Schone Kunsten Gent:
          translations:
            en: Museum of Fine Arts Ghent
            nl: Museum voor Schone Kunsten Gent
          creditline:
            en: '<p>The original TIFF files of this work, in highest resolution and color-coded, can be ordered from <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). If this image is used for a printed publication or a commercial product, MSK Gent would appreciate having three copies sent to MSK Gent, Hofbouwlaan 28, B-9000 Gent. More information: <a href="mailto:museum.msk@stad.gent">museum.msk@stad.gent</a>.</p>'
            nl: '<p>De originele TIFF-bestanden van dit werk, in hoogste resolutie en met kleurencode, kunnen worden besteld bij <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). Wanneer dit beeld gebruikt wordt voor een gedrukte publicatie of een commercieel product, dan vraagt MSK Gent dat drie exemplaren worden toegestuurd naar MSK Gent, Hofbouwlaan 28, B-9000 Gent. Meer info: <a href="mailto:museum.msk@stad.gent">museum.msk@stad.gent</a>.</p>'
        Mu.ZEE, Kunstmuseum aan zee:
          translations:
            en: Mu.ZEE, Art museum at the seaside
            nl: Mu.ZEE, Kunstmuseum aan zee
          creditline:
            en: '<p>The original TIFF files of this work, in highest resolution and color-coded, can be ordered from <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). If this image is used for a printed publication or a commercial product, Mu.ZEE would appreciate having three copies sent to Mu.ZEE, Romestraat 11, 8400 Oostende, Belgium. More information: <a href="mailto:info@muzee.be">info@muzee.be</a>.</p>'
            nl: '<p>De originele TIFF-bestanden van dit werk, in hoogste resolutie en met kleurencode, kunnen worden besteld bij <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). Wanneer dit beeld gebruikt wordt voor een gedrukte publicatie of een commercieel product, dan vraagt Mu.ZEE dat drie exemplaren worden toegestuurd naar Mu.ZEE, Romestraat 11, 8400 Oostende. Meer info: <a href="mailto:info@muzee.be">info@muzee.be</a>.</p>'
        Musea Brugge:
          translations:
            en: Musea Bruges
            nl: Musea Brugge
          creditline:
            en: '<p>The original TIFF files of this work, in highest resolution and color-coded, can be ordered from <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). If this image is used for a printed publication or a commercial product, Musea Brugge would appreciate having three copies sent to Musea Brugge, Dijver 12, 8000 Brugge. More information: <a href="mailto:musea@brugge.be">musea@brugge.be</a>.</p>'
            nl: '<p>De originele TIFF-bestanden van dit werk, in hoogste resolutie en met kleurencode, kunnen worden besteld bij <a href="https://artinflanders.be">Art in Flanders</a> (meemoo). Wanneer dit beeld gebruikt wordt voor een gedrukte publicatie of een commercieel product, dan vraagt Musea Brugge dat drie exemplaren worden toegestuurd naar Musea Brugge, Dijver 12, 8000 Brugge. Meer info: <a href="mailto:musea@brugge.be">musea@brugge.be</a>.</p>'

    iiif_rights_source: 'copyrightnoticeofart'
    iiif_behavior: 'iiifbehavior'
    iiif_label:
      en: 'en-titleartwork'
      nl: 'nl-titleartwork'
    iiif_required_statement:
      label:
        en: 'Collection'
        nl: 'Collectie'
      value:
        en: 'publisher'
        nl: 'publisher'
      extra_info:
        en: '{{ imagehub.credit_extra_info_en }}'
        nl: '{{ imagehub.credit_extra_info_nl }}'
    iiif_metadata_fields:
      title:
        label:
          en: 'Title'
          nl: 'Titel'
        value:
          en: 'en-titleartwork'
          nl: 'nl-titleartwork'
      creator:
        label:
          en: 'Creator'
          nl: 'Vervaardiger'
        value:
          en: 'creatorofartworkobje'
          nl: 'creatorofartworkobje'
      date:
        label:
          en: 'Date created'
          nl: 'Vervaardigingsdatum'
        value:
          nl: 'datecreatedofartwork'
          en: 'datecreatedofartwork'
      inventory_number:
        label:
          en: 'Inventory no.'
          nl: 'Inventarisnummer'
        value:
          en: 'sourceinvnr'
          nl: 'sourceinvnr'
      creator_of_image:
        label:
          en: 'Photographer'
          nl: 'Fotograaf'
        value:
          en: 'creatorofimage'
          nl: 'creatorofimage'
      photographer:
        label:
          en: 'Photographer'
          nl: 'Fotograaf'
        value:
          en: 'photographer'
          nl: 'photographer'
      description:
        label:
          en: 'Description'
          nl: 'Beschrijving'
        value:
          en: 'description'
          nl: 'description'
